import type { BrandConfig } from './types';
export default {
  appName: 'TestScrape',
  appDescription: 'Verification fixture for the brand-config layer',
  actionTitle: 'Open TestScrape',
  welcomeHeading: 'Welcome to TestScrape',
  notificationTitle: 'TestScrape',
  logPrefix: '[TestScrape]',
  tagline: 'Verification fixture',
  searchVarPlaceholder: 'TestCo One\nTestCo Two\nTestCo Three',
  fontFamily: 'system-ui, sans-serif',
  iconDir: 'test-brand/icons',
  // TODO: replace with teal icons
  defaultServerUrl: 'http://localhost:5099',
  palette: {
    primary: '#0D7C66',
    primaryRgb: '13, 124, 102',
    primaryLight: '#1FA383',
    secondary: '#FFB800',
    bgTint: '#E8F7F2',
    textDark: '#1A2E2A',
    textLight: '#6B7C78',
    bgWhite: '#FFFFFF',
    bgLight: '#F5F8F7',
    bgHover: '#E0EEE9',
    border: '#C5DDD4',
    danger: '#D32F2F',
    dangerLight: '#FFEBEE',
    success: '#2E7D32',
    successLight: '#E8F5E9',
    warning: '#F57F17',
    warningLight: '#FFF8E1',
    infoLight: '#E8F7F2',
  },
} satisfies BrandConfig;
